# NumPy

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
arr.ndim

1

In [ ]:
a = np.array([])
a.ndim


1

In [ ]:
a = np.array([[]])
a.ndim

2

In [ ]:
a = np.array([[[[]]]])
a.ndim
a.shape

(1, 1, 1, 0)

In [ ]:
range = np.arange(1,10)
range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
range = np.arange(1,10, 2) # start,stop -> never included,step value
range

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.linspace(0,1, 10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
# logarithmic scale array -> 10^1 to 10^3 ... 3 points
arr = np.logspace (1,3, 3)
arr

array([  10.,  100., 1000.])

In [ ]:
# np.logspace( start, ending -> power, 3 -> number or value)

In [ ]:
# np.zeros -> array full of zeros
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#array full of ones
arr = np.ones([4,2])
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
arr = np.full(10,2)# -> create an array of any value
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
arr = np.full([2,4], 7) # [row,column], dfault value
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
arr = np.empty([2,3]) #uninitialised array -> create an array without setting any kinda value
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.random.rand(10) # -> random floats(0 - 1)
arr

array([0.11518571, 0.97618531, 0.1378401 , 0.1088088 , 0.23537495,
       0.93004456, 0.83100458, 0.06625885, 0.73684418, 0.58603523])

In [ ]:
arr = np.random.rand(2,3) # no using of square brackets
arr

array([[0.18692559, 0.23930409, 0.48006341],
       [0.17255052, 0.61099861, 0.87319353]])

In [ ]:
arr = np.random.randn(2,3) # -> randoms no. having normal distributions
arr

array([[-0.19755962,  0.23836601,  0.24825687],
       [ 0.9856141 , -1.43477932, -0.14787273]])

In [ ]:
arr = np.random.randint(10,100) # -> random integers
arr

49

In [ ]:
arr = np.random.randint(10,100, size= (2,3)) # -> start, stop, and dimensions/number
arr

array([[65, 97, 35],
       [26, 75, 38]])

# ***NumPy Data and Type and Type casting***

In [ ]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array([1,2,3.1,4,5]) # numpy doesn't allows to be had in an array
arr

array([1. , 2. , 3.1, 4. , 5. ])

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
lst = ["string",1, 2, 5.6]
arr = np.array(lst)
arr

array(['string', '1', '2', '5.6'], dtype='<U32')

In [ ]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr = np.array([1,2,3,4], dtype = np.float64)
arr.dtype

dtype('float64')

In [ ]:
arr = np.array([1,2,3,4], dtype = np.float32)
arr.dtype

dtype('float32')

In [ ]:
# type casting -> astype()
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [ ]:
n_arr = arr.astype(np.float64)
n_arr

array([1., 2., 3.])

In [ ]:
n_arr.dtype

dtype('float64')

In [ ]:
#Type Casting 'Errors'
arr = np.array(['1','2','hello'])
arr2 = arr.astype(np.int64)
arr2

ValueError: invalid literal for int() with base 10: np.str_('hello')

*how to create a multi dimentional array *

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.size

6

In [ ]:
arr.itemsize # size of one array in bytes

8

***Array Reshaping -> Reshape,Ravel,Flatten***

In [ ]:
#reshape
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
reshape2 = reshaped.reshape(3,2)
reshape2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#ravel -> convert 1D array
ravel = reshape2.ravel

In [ ]:
ravel[0] = 100
print(reshape2)


NameError: name 'ravel' is not defined

In [ ]:
#flatten -> 1D array
# -> return a copy of the array
flat = reshape2.flatten()
flat

array([1, 2, 3, 4, 5, 6])

In [ ]:
flat[0] = 1
flat

array([1, 2, 3, 4, 5, 6])

In [ ]:
reshape2 #no changes(has 0 connection with the orignal array)

array([[1, 2],
       [3, 4],
       [5, 6]])

### ***arithmetic oprations on array***

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])


In [ ]:
#addition

print(a+b)

[5 7 9]


In [ ]:
#subtraction
print(a-b)

[-3 -3 -3]


In [ ]:
#division
print(a/b)

[0.25 0.4  0.5 ]


In [ ]:
#integer values
print(b//a)

[4 2 2]


In [ ]:
#multiplication
print(a*b)

[ 4 10 18]


In [ ]:
#modulus
print(b % a)# -> gives the reminder

[0 1 0]


In [ ]:
#exponents
print(a**b)

[  1  32 729]


*Universal Functions or unifuncs*

In [ ]:
arr = np.array([1,4,9,16])

In [ ]:
#square root -> np.sqrt()
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [ ]:
#exponentials -> np.exp -> e^x where x is any integer
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [ ]:
#sin function-> np.sin

angles = np.array([0,np.pi/2,np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [ ]:
#cos function-> np.sin

angles = np.array([0,np.pi/2,np.pi])
print(np.cos(angles))

[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [ ]:
#tan function-> np.sin

angles = np.array([0,np.pi/2,np.pi])
print(np.tan(angles))

[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


***indexing and slicing***

In [ ]:
a = [1,2,3,4,5]
a[-1: -4 : -1]

[5, 4, 3]

In [ ]:
a[: :2]

[1, 3, 5]

In [ ]:
arr = np.array([10,20,30,40,50])
# index = 0,2,4
arr[0: :2]

array([10, 30, 50])

In [ ]:
#Negative Indexing
print(arr[-1])


50


In [ ]:
# multi dimentional slicing
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])


In [ ]:
print(matrix[0:2])

[[1 2 3]
 [4 5 6]]


In [ ]:
print(matrix[1 : ,1 :])

[[5 6]
 [8 9]]


In [ ]:
#np.take -> biultin function to perform indexing or slicing
arr = np.array([10,20,30,40,50])
ind = [0, 2]
print(np.take(arr, ind))

[10 30]


In [ ]:
#itrating with nditer()

In [ ]:
arr = np.array([[1,2],[3,4]])

In [ ]:
for x in np.nditer(arr):
 print(x, end = " ")

1 2 3 4 

In [ ]:
#ndnumerater() -> both index + vlaue

for ind, x in np.ndenumerate(arr):
  print(ind, x)



(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [ ]:
# Views vs Copies

arr = np.array([1,2,3,4,5])
veiw = arr[1:3]
veiw


array([2, 3])

In [ ]:
veiw[0] = 200
veiw

array([200,   3])

In [ ]:
arr

array([  1, 200,   3,   4,   5])

In [ ]:
#copy
copy = arr[1:3].copy()
copy

array([200,   3])

In [ ]:
copy[0] = 2
copy

array([2, 3])

In [ ]:
arr

array([  1, 200,   3,   4,   5])

In [ ]:
#Transporse -> interchaning of rows and colomns
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [ ]:
print(arr.transpose())

[[1 3]
 [2 4]]


In [ ]:
#Swapaxes -> swap two spedcific axes of a matrix
arr = np.array([[[1,2],[3,4]]])
arr.shape

(1, 2, 2)

In [ ]:
swap = np.swapaxes(arr, 0, 1)
swap

array([[[1, 2]],

       [[3, 4]]])

In [ ]:
swap.shape

(2, 1, 2)

In [ ]:
#concatination:

a = np.array([1,2])
b = np.array([3,4])

In [ ]:
combine = np.concatenate((a,b))
combine

array([1, 2, 3, 4])

In [ ]:
#Vertical stack
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [ ]:
print(np.vstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
print(np.stack((arr1, arr2), axis = 0))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Horizontal stack
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [ ]:
print(np.hstack((arr1, arr2)))

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
print(np.stack((arr1, arr2), axis = 1))

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [ ]:
#Spliting arrays:
arr1 = np.array([[1,2],[3,4],[5,6],[7,8]])
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
print(np.split(arr1, 2)) #spliting twice

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [ ]:
print(np.split(arr1, 4))#spliting into four seperete arrays

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [ ]:
#Repeting : -> repeating each element of array sepretly
arr = np.array([1,2,3])
print(np.repeat(arr,2))

[1 1 2 2 3 3]


In [ ]:
#Tile : -> repeating entire array
arr = np.array([1,2,3])
print(np.tile(arr,2))

[1 2 3 1 2 3]


In [ ]:
#Agregate Functions:
arr = np.array([1,2,3])
print(np.sum(arr))

6


In [ ]:
np.mean(arr)

np.float64(2.0)

In [ ]:
np.median(arr)

np.float64(2.0)

In [ ]:
np.std(arr)#standard deviation

np.float64(0.816496580927726)

In [ ]:
np.var(arr)#variation

np.float64(0.6666666666666666)

In [ ]:
np.min(arr)

np.int64(1)

In [ ]:
np.max(arr)

np.int64(3)

In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(np.sum(matrix, axis = 1))

[ 6 15 24]


In [ ]:
#Cumilative Oprations -> Running Total
arr

array([1, 2, 3])

In [ ]:
print(np.cumsum(arr))

[1 3 6]


In [ ]:
#Cumilative Product -> running product
print(np.cumprod(arr))

[1 2 6]


# ***Conditional Based choices***

In [ ]:
#Where

arr

array([1, 2, 3])

In [ ]:
result = np.where(arr<2,"low", "heigh")
result

array(['low', 'heigh', 'heigh'], dtype='<U5')

In [ ]:
arr = np.array([10,25,35,50])
arr

array([10, 25, 35, 50])

In [ ]:
#Argwhere -> give a colomn form for 2D array
print(np.argwhere(arr>20))

[[1]
 [2]
 [3]]


In [ ]:
mask = np.logical_and(arr>15 , arr<35)
mask

array([False,  True, False, False])

In [ ]:
print(np.argwhere(matrix > 5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [ ]:
#Logical "and":
arr = np.array([100,2,3,4,5,6])
arr

array([100,   2,   3,   4,   5,   6])

In [ ]:
mask = np.logical_and(arr>3, arr <6)
mask

array([False, False, False,  True,  True, False])

In [ ]:
arr[mask]

array([4, 5])

In [ ]:
#Logical "or":
mask = np.logical_or(arr < 4, arr > 5)
mask

array([ True,  True,  True, False, False,  True])

In [ ]:
arr[mask]

array([100,   2,   3,   6])

In [ ]:
arr2 = np.array([0,1,5,0,5])
arr2

array([0, 1, 5, 0, 5])

In [ ]:
print(np.nonzero(arr2))

(array([1, 2, 4]),)


In [ ]:
# Broadcasting
image = np.array([[200,150],[100,250]])
image

array([[200, 150],
       [100, 250]])

In [ ]:
brightness = image + 50
brightness

array([[250, 200],
       [150, 300]])

In [ ]:
# Vectorisation :

#np.vectorize -> converts a regular function to be applied on an array.

In [ ]:
#slower than a loop but gives a veiw ofp a syntax
def square(x):
    return x*x

vfunc = np.vectorize(square)

In [ ]:
arr

array([100,   2,   3,   4,   5,   6])

In [ ]:
print(vfunc(arr))

[10000     4     9    16    25    36]


In [ ]:
#Dealing with missing values
#np.nan -> npt a number

In [ ]:
a = np.array([1,2,np.nan,4])
a

array([ 1.,  2., nan,  4.])

In [ ]:
#np.inf and -np.inf -> +ve and -ve infinites


In [ ]:
#np.isnan
#np.isinf
#np.isfinite

#--> these are the funcs that are used to detect null ,finite and infinte values


In [ ]:
print(np.isnan(a))

[False False  True False]


In [ ]:
b = np.array([1,np.nan,np.inf,10.2,40])
b

array([ 1. ,  nan,  inf, 10.2, 40. ])

In [ ]:
print(np.isinf(b))

[False False  True False False]


In [ ]:
new_b = np.nan_to_num(b)#Remove not a number/infinte values.
new_b

array([1.00000000e+000, 0.00000000e+000, 1.79769313e+308, 1.02000000e+001,
       4.00000000e+001])